language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default


php:
  - 7.0
  - 7.1

env:
  matrix:
   - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
   - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
   - DB=pgsql MOODLE_BRANCH=master
   - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
   - DB=mysqli MOODLE_BRANCH=master

matrix:
 allow_failures:
  - env: DB=pgsql MOODLE_BRANCH=master
  - env: DB=mysqli MOODLE_BRANCH=master
 fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install v8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
#      - moodle-plugin-ci phpcpd # temporarily disabled
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
      - moodle-plugin-ci validate

install:
  - moodle-plugin-ci install

# Unit tests and behat tests against full matrix.
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - test